(* rv_softfloat.ml — GENERATED by scripts/gen_rv_softfloat.py from
   contrib/softfloat. DO NOT EDIT: regenerate and commit, and
   `sh scripts/gen_rv_softfloat.sh --check` diffs it on every run.

   Every top-level name is renamed into a private namespace so that a
   user program's own `add` cannot become what float `+` calls. See the
   generator for why that is not paranoia. *)

let contents = {sf|
// ---- contrib/softfloat/limbs.mere ----
// contrib/softfloat/limbs — a 90-bit unsigned integer as six 15-bit limbs.
//
// The working width for adding two doubles. A significand is 53 bits; aligning
// one against the other needs room below it for the guard and round bits and a
// sticky, and room above for the carry out of an addition. Six limbs is 90
// bits, which is more than either needs and keeps the shifts from having to be
// clever.
//
// 15 bits per limb for the reason the fraction uses them: a product of two
// limbs must fit the narrowest int any backend has, RV32I's signed 32-bit
// word. Addition needs far less, but one limb width for the whole library
// means the multiply that comes later does not get a second one.
//
// Little-endian: l0 is the low 15 bits. Nothing here mentions `float`.

type L6__rv = { l5: int, l4: int, l3: int, l2: int, l1: int, l0: int };

let __sf_lmask = 32767;            // 2^15 - 1
let __sf_lbits = 15;

let __sf_l6_zero = L6__rv { l5 = 0, l4 = 0, l3 = 0, l2 = 0, l1 = 0, l0 = 0 };

let __sf_l6_is_zero = fn (a: L6__rv) ->
  a.l5 == 0 && a.l4 == 0 && a.l3 == 0 && a.l2 == 0 && a.l1 == 0 && a.l0 == 0;

// Compare magnitudes: -1, 0 or 1. Most significant limb first.
let __sf_l6_cmp = fn (a: L6__rv) -> fn (b: L6__rv) ->
  if a.l5 != b.l5 then (if a.l5 < b.l5 then 0 - 1 else 1)
  else if a.l4 != b.l4 then (if a.l4 < b.l4 then 0 - 1 else 1)
  else if a.l3 != b.l3 then (if a.l3 < b.l3 then 0 - 1 else 1)
  else if a.l2 != b.l2 then (if a.l2 < b.l2 then 0 - 1 else 1)
  else if a.l1 != b.l1 then (if a.l1 < b.l1 then 0 - 1 else 1)
  else if a.l0 != b.l0 then (if a.l0 < b.l0 then 0 - 1 else 1)
  else 0;

// Sum, discarding any carry out of l5. The caller keeps the result in range by
// leaving a limb of headroom, which every use here does.
let __sf_l6_add = fn (a: L6__rv) -> fn (b: L6__rv) ->
  let s0 = a.l0 + b.l0 in
  let s1 = a.l1 + b.l1 + bit_shr s0 __sf_lbits in
  let s2 = a.l2 + b.l2 + bit_shr s1 __sf_lbits in
  let s3 = a.l3 + b.l3 + bit_shr s2 __sf_lbits in
  let s4 = a.l4 + b.l4 + bit_shr s3 __sf_lbits in
  let s5 = a.l5 + b.l5 + bit_shr s4 __sf_lbits in
  L6__rv { l5 = bit_and s5 __sf_lmask, l4 = bit_and s4 __sf_lmask, l3 = bit_and s3 __sf_lmask,
       l2 = bit_and s2 __sf_lmask, l1 = bit_and s1 __sf_lmask, l0 = bit_and s0 __sf_lmask };

// a - b, for a >= b. Borrowing is done by adding the base before subtracting so
// no intermediate goes negative -- a negative limb would be a different bug on
// every backend, since the widths differ.
let __sf_l6_sub = fn (a: L6__rv) -> fn (b: L6__rv) ->
  let base = 32768 in
  let d0 = a.l0 - b.l0 + base in
  let c0 = if d0 < base then 1 else 0 in
  let d1 = a.l1 - b.l1 - c0 + base in
  let c1 = if d1 < base then 1 else 0 in
  let d2 = a.l2 - b.l2 - c1 + base in
  let c2 = if d2 < base then 1 else 0 in
  let d3 = a.l3 - b.l3 - c2 + base in
  let c3 = if d3 < base then 1 else 0 in
  let d4 = a.l4 - b.l4 - c3 + base in
  let c4 = if d4 < base then 1 else 0 in
  let d5 = a.l5 - b.l5 - c4 + base in
  L6__rv { l5 = bit_and d5 __sf_lmask, l4 = bit_and d4 __sf_lmask, l3 = bit_and d3 __sf_lmask,
       l2 = bit_and d2 __sf_lmask, l1 = bit_and d1 __sf_lmask, l0 = bit_and d0 __sf_lmask };


let __sf_l6_limb = fn (a: L6__rv) -> fn (i: int) ->
  if i == 0 then a.l0 else if i == 1 then a.l1 else if i == 2 then a.l2
  else if i == 3 then a.l3 else if i == 4 then a.l4 else if i == 5 then a.l5
  else 0;

let __sf_l6_of_limbs = fn (l5: int) -> fn (l4: int) -> fn (l3: int) ->
                  fn (l2: int) -> fn (l1: int) -> fn (l0: int) ->
  L6__rv { l5 = bit_and l5 __sf_lmask, l4 = bit_and l4 __sf_lmask, l3 = bit_and l3 __sf_lmask,
       l2 = bit_and l2 __sf_lmask, l1 = bit_and l1 __sf_lmask, l0 = bit_and l0 __sf_lmask };

// shift left by one bit, discarding the bit out of the top
let __sf_l6_shl1 = fn (a: L6__rv) ->
  __sf_l6_of_limbs
    (bit_or (bit_shl a.l5 1) (bit_shr a.l4 14))
    (bit_or (bit_shl a.l4 1) (bit_shr a.l3 14))
    (bit_or (bit_shl a.l3 1) (bit_shr a.l2 14))
    (bit_or (bit_shl a.l2 1) (bit_shr a.l1 14))
    (bit_or (bit_shl a.l1 1) (bit_shr a.l0 14))
    (bit_shl a.l0 1);

// shift right by one bit; returns the bit that fell off, so a caller can build
// a sticky without looking inside
let __sf_l6_shr1 = fn (a: L6__rv) ->
  __sf_l6_of_limbs
    (bit_shr a.l5 1)
    (bit_or (bit_shr a.l4 1) (bit_shl (bit_and a.l5 1) 14))
    (bit_or (bit_shr a.l3 1) (bit_shl (bit_and a.l4 1) 14))
    (bit_or (bit_shr a.l2 1) (bit_shl (bit_and a.l3 1) 14))
    (bit_or (bit_shr a.l1 1) (bit_shl (bit_and a.l2 1) 14))
    (bit_or (bit_shr a.l0 1) (bit_shl (bit_and a.l1 1) 14));

let __sf_l6_low_bit = fn (a: L6__rv) -> bit_and a.l0 1;

let rec __sf_l6_shl = fn (a: L6__rv) -> fn (n: int) ->
  if n <= 0 then a else __sf_l6_shl (__sf_l6_shl1 a) (n - 1);

// Shift right by n, returning the value and whether any 1 was shifted out.
// The sticky is the whole reason this is not just a shift: rounding needs to
// know that something was lost, not only what the last bit was.
let rec __sf_l6_shr_sticky_go = fn (a: L6__rv) -> fn (n: int) -> fn (st: int) ->
  if n <= 0 then (a, st)
  else __sf_l6_shr_sticky_go (__sf_l6_shr1 a) (n - 1) (bit_or st (__sf_l6_low_bit a));
let __sf_l6_shr_sticky = fn (a: L6__rv) -> fn (n: int) -> __sf_l6_shr_sticky_go a n 0;

// number of bits needed to hold the value; 0 for zero
let rec __sf_l6_bitlen_limb = fn (v: int) -> fn (acc: int) ->
  if v == 0 then acc else __sf_l6_bitlen_limb (bit_shr v 1) (acc + 1);
let __sf_l6_bitlen = fn (a: L6__rv) ->
  if a.l5 != 0 then 75 + __sf_l6_bitlen_limb a.l5 0
  else if a.l4 != 0 then 60 + __sf_l6_bitlen_limb a.l4 0
  else if a.l3 != 0 then 45 + __sf_l6_bitlen_limb a.l3 0
  else if a.l2 != 0 then 30 + __sf_l6_bitlen_limb a.l2 0
  else if a.l1 != 0 then 15 + __sf_l6_bitlen_limb a.l1 0
  else __sf_l6_bitlen_limb a.l0 0;

// bit i of the 90, counting from 0. Rounding needs to look at three specific
// bits and normalisation at one, and reaching into the limbs from outside would
// put the 15 in two files.
let __sf_l6_bit = fn (a: L6__rv) -> fn (i: int) ->
  let li = i / 15 in
  bit_and (bit_shr (__sf_l6_limb a li) (i - li * 15)) 1;

let __sf_l6_one = __sf_l6_of_limbs 0 0 0 0 0 1;

// A backend's own int, as limbs. Five limbs is 75 bits, wider than any
// backend's int, so this loses nothing anywhere. On a 32-bit target the shifts
// past 31 produce zero, which is the right answer there because the value
// cannot have those bits.
let __sf_l6_of_int = fn (n: int) ->
  __sf_l6_of_limbs 0 (bit_and (bit_shr n 60) __sf_lmask) (bit_and (bit_shr n 45) __sf_lmask)
                (bit_and (bit_shr n 30) __sf_lmask) (bit_and (bit_shr n 15) __sf_lmask)
                (bit_and n __sf_lmask);

// and back, for values that fit. Limb 5 is dropped: a caller wanting more than
// 75 bits has to ask a different question.
let __sf_l6_to_int = fn (a: L6__rv) ->
  bit_or (bit_or (bit_or (bit_shl a.l4 60) (bit_shl a.l3 45))
                 (bit_or (bit_shl a.l2 30) (bit_shl a.l1 15))) a.l0;
// ---- contrib/softfloat/softfloat.mere ----
// contrib/softfloat — an IEEE 754 double as integers a 32-bit target can hold.
//
// This file never mentions `float`. That is the point: the narrowest backend
// (RV32I) has no float in its value model, so a library that needs one there
// cannot be written in terms of one. The bridge to hardware doubles lives in
// the gate that checks this code, not in the code.
//
// Representation. A double is 64 bits: sign(1) exponent(11) fraction(52).
// The fraction is held little-endian in FOUR 15-BIT LIMBS. 15 because a
// product of two limbs must fit the narrowest int any backend has, which is
// RV32I's signed 32-bit word: 15 + 15 = 30 bits, and the sign bit is left
// alone. Splitting into 32-bit halves the way `float_bits_hi` / `float_bits_lo`
// do is the obvious alternative and it does not work here -- those return
// UNSIGNED 32-bit values (`float_bits_hi (-1.0)` is 3220176896) and this
// target's int is signed and 32 wide, so the half does not fit either.

type Sf__rv = { sign: int, exp: int, f3: int, f2: int, f1: int, f0: int };

let __sf_limb_mask = 32767;        // 2^15 - 1
let __sf_exp_mask = 2047;          // 2^11 - 1

// The raw fields, unchecked. Callers that decode a bit pattern use this.
let __sf_mk = fn (sign: int) -> fn (exp: int) -> fn (f3: int) -> fn (f2: int) ->
         fn (f1: int) -> fn (f0: int) ->
  Sf__rv { sign = bit_and sign 1, exp = bit_and exp __sf_exp_mask,
    f3 = bit_and f3 __sf_limb_mask, f2 = bit_and f2 __sf_limb_mask,
    f1 = bit_and f1 __sf_limb_mask, f0 = bit_and f0 __sf_limb_mask };

let __sf_zero = __sf_mk 0 0 0 0 0 0;
let __sf_neg_zero = __sf_mk 1 0 0 0 0 0;
let __sf_inf = __sf_mk 0 2047 0 0 0 0;
let __sf_neg_inf = __sf_mk 1 2047 0 0 0 0;
// Any non-zero fraction with a full exponent is a NaN; this is the quiet one
// every backend's hardware produces for 0.0 / 0.0.
let __sf_nan = __sf_mk 0 2047 64 0 0 0;

// --- classification -------------------------------------------------------

let __sf_frac_is_zero = fn (a: Sf__rv) -> a.f3 == 0 && a.f2 == 0 && a.f1 == 0 && a.f0 == 0;
let __sf_is_nan = fn (a: Sf__rv) -> a.exp == 2047 && not (__sf_frac_is_zero a);
let __sf_is_inf = fn (a: Sf__rv) -> a.exp == 2047 && __sf_frac_is_zero a;
let __sf_is_zero = fn (a: Sf__rv) -> a.exp == 0 && __sf_frac_is_zero a;
// Subnormals carry no implicit leading 1, which is why they need a name here
// rather than falling out of the exponent test.
let __sf_is_subnormal = fn (a: Sf__rv) -> a.exp == 0 && not (__sf_frac_is_zero a);
let __sf_is_finite = fn (a: Sf__rv) -> a.exp != 2047;

// --- sign -----------------------------------------------------------------

// Flipping the sign is defined on every value, NaN included -- IEEE 754 says
// negation is a bit operation, not an arithmetic one, so it does not quiet a
// signalling NaN or raise anything.
let __sf_neg = fn (a: Sf__rv) ->
  Sf__rv { sign = bit_xor a.sign 1, exp = a.exp, f3 = a.f3, f2 = a.f2, f1 = a.f1, f0 = a.f0 };
let __sf_abs = fn (a: Sf__rv) ->
  Sf__rv { sign = 0, exp = a.exp, f3 = a.f3, f2 = a.f2, f1 = a.f1, f0 = a.f0 };
let __sf_is_neg = fn (a: Sf__rv) -> a.sign == 1;

// --- comparison -----------------------------------------------------------

// Magnitude order, ignoring the sign. The fields are laid out most-significant
// first on purpose: exponent, then limbs from f3 down, so this is a plain
// lexicographic walk.
let rec __sf_cmp_mag = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  if a.exp != b.exp then (if a.exp < b.exp then 0 - 1 else 1)
  else if a.f3 != b.f3 then (if a.f3 < b.f3 then 0 - 1 else 1)
  else if a.f2 != b.f2 then (if a.f2 < b.f2 then 0 - 1 else 1)
  else if a.f1 != b.f1 then (if a.f1 < b.f1 then 0 - 1 else 1)
  else if a.f0 != b.f0 then (if a.f0 < b.f0 then 0 - 1 else 1)
  else 0;

// IEEE equality: NaN is equal to nothing, and -0.0 equals +0.0. Neither falls
// out of a bit comparison, which is why this is not one.
let __sf_eq = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  if __sf_is_nan a || __sf_is_nan b then false
  else if __sf_is_zero a && __sf_is_zero b then true
  else a.sign == b.sign && __sf_cmp_mag a b == 0;

let __sf_lt = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  if __sf_is_nan a || __sf_is_nan b then false
  else if __sf_is_zero a && __sf_is_zero b then false
  else if a.sign != b.sign then a.sign == 1
  else if a.sign == 0 then __sf_cmp_mag a b < 0
  else __sf_cmp_mag a b > 0;

let __sf_gt = fn (a: Sf__rv) -> fn (b: Sf__rv) -> __sf_lt b a;
let __sf_le = fn (a: Sf__rv) -> fn (b: Sf__rv) -> if __sf_is_nan a || __sf_is_nan b then false else not (__sf_lt b a);
let __sf_ge = fn (a: Sf__rv) -> fn (b: Sf__rv) -> if __sf_is_nan a || __sf_is_nan b then false else not (__sf_lt a b);
// ---- contrib/softfloat/add.mere ----
// contrib/softfloat/add — IEEE 754 addition, in integers only.
//
// The working significand is the 53-bit one shifted left by 3, so the three
// bits below it are the guard, the round and the sticky that
// round-to-nearest-even needs. A normal's leading bit then sits at 55.
//
// The exponent carried around is not the field but the effective one: a value
// is `significand * 2^(E - 1075)`, with E = the exponent field for normals and
// E = 1 for subnormals. That single convention is why subnormals need no
// separate path here -- they arrive with a significand that happens to be
// small, and the normalisation step that cannot lower E below 1 puts them back.

// bit 52 lives in limb 3 at position 7
let __sf_hidden_bit = 128;
// the quiet bit is fraction bit 51, which is limb 3 bit 6
let __sf_quiet_bit = 64;

// A NaN handed back as a result comes back QUIET. A signalling one arriving as
// an operand is the only case where the answer is not the operand unchanged --
// the hardware sets bit 51 and keeps the payload, which is what this does.
let __sf_quiet = fn (a: Sf__rv) -> __sf_mk a.sign 2047 (bit_or a.f3 __sf_quiet_bit) a.f2 a.f1 a.f0;
let __sf_is_snan = fn (a: Sf__rv) -> __sf_is_nan a && bit_and a.f3 __sf_quiet_bit == 0;

let __sf_sig_of = fn (a: Sf__rv) ->
  let h = if a.exp == 0 then 0 else __sf_hidden_bit in
  __sf_l6_shl (__sf_l6_of_limbs 0 0 (a.f3 + h) a.f2 a.f1 a.f0) 3;

let __sf_eff_exp = fn (a: Sf__rv) -> if a.exp == 0 then 1 else a.exp;

// Pack a significand (still shifted left by 3) and an effective exponent back
// into a double, rounding to nearest with ties to even.
let __sf_pack = fn (sign: int) -> fn (s0: L6__rv) -> fn (e0: int) -> fn (st0: int) ->
  // normalise: a carry out of bit 55 shifts down, leading zeros shift up, and
  // the shift up stops at E = 1 because there is no exponent below it
  let rec down = fn (s: L6__rv) -> fn (e: int) -> fn (st: int) ->
    if __sf_l6_bitlen s <= 56 then (s, e, st)
    else let p = __sf_l6_shr_sticky s 1 in down (fst p) (e + 1) (bit_or st (snd p)) in
  let (sd, ed0, std0) = down s0 e0 st0 in
  // Gradual underflow. Addition never gets here -- both its exponents are at
  // least 1 -- but a product's can be far below, and the answer is not zero: it
  // is a subnormal, reached by shifting right until E is 1 and rounding there.
  let (sd2, ed, std) =
    if ed0 >= 1 then (sd, ed0, std0)
    else
      // Past 60 bits everything left is sticky, and division can arrive here
      // with an exponent thousands below 1 (a normalised subnormal divided by a
      // large normal), which would otherwise be that many single-bit shifts.
      let n = if 1 - ed0 > 60 then 60 else 1 - ed0 in
      let p2 = __sf_l6_shr_sticky sd n in
      (fst p2, 1, bit_or std0 (bit_or (snd p2) (if __sf_l6_is_zero (fst p2) then 1 else 0))) in
  let rec up = fn (s: L6__rv) -> fn (e: int) ->
    if e <= 1 then (s, e)
    else if __sf_l6_bitlen s >= 56 then (s, e)
    else if __sf_l6_is_zero s then (s, e)
    else up (__sf_l6_shl s 1) (e - 1) in
  let (s1, e1) = up sd2 ed in
  // round to nearest, ties to even: the round bit decides, and a tie is broken
  // by whether anything was lost below it or the retained bit is odd
  let lsb = __sf_l6_bit s1 3 in
  let rnd = __sf_l6_bit s1 2 in
  let sticky = bit_or (bit_or (__sf_l6_bit s1 1) (__sf_l6_bit s1 0)) std in
  let s2 = if rnd == 1 && (sticky == 1 || lsb == 1) then __sf_l6_add s1 (__sf_l6_shl __sf_l6_one 3) else s1 in
  // rounding can carry out of the top
  let (sr, e3) = if __sf_l6_bitlen s2 > 56 then (fst (__sf_l6_shr_sticky s2 1), e1 + 1) else (s2, e1) in
  let s3 = fst (__sf_l6_shr_sticky sr 3) in
  if e3 >= 2047 then (if sign == 1 then __sf_neg_inf else __sf_inf)
  else if __sf_l6_bit s3 52 == 1 then __sf_mk sign e3 (bit_and s3.l3 127) s3.l2 s3.l1 s3.l0
  else if __sf_l6_is_zero s3 then __sf_mk sign 0 0 0 0 0
  else __sf_mk sign 0 s3.l3 s3.l2 s3.l1 s3.l0;   // still subnormal: E was 1

let __sf_add = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  // NaN first, and the first NaN operand is the answer -- what the hardware
  // does, checked rather than assumed (test/float/softfloat_add.mere).
  // A SIGNALLING NaN outranks a quiet one, whichever side it is on: the answer
  // is the signalling one, quieted. Among quiet NaNs the first operand wins.
  // Both halves of that were measured, not assumed -- the second half cost a
  // gate failure on `quiet + signalling`, where returning the first NaN gave
  // the wrong 64 bits.
  if __sf_is_snan a then __sf_quiet a
  else if __sf_is_snan b then __sf_quiet b
  else if __sf_is_nan a then __sf_quiet a
  else if __sf_is_nan b then __sf_quiet b
  else if __sf_is_inf a then
    (if __sf_is_inf b && a.sign != b.sign then __sf_nan else a)
  else if __sf_is_inf b then b
  else if __sf_is_zero a && __sf_is_zero b then
    // +0 + -0 is +0 under round-to-nearest; only two negative zeros give one
    (if a.sign == 1 && b.sign == 1 then __sf_neg_zero else __sf_zero)
  else if __sf_is_zero a then b
  else if __sf_is_zero b then a
  else
    let ea = __sf_eff_exp a in let eb = __sf_eff_exp b in
    let sa = __sf_sig_of a in let sb = __sf_sig_of b in
    // order by magnitude so the subtraction below never goes negative
    let a_first =
      if ea != eb then ea > eb else __sf_l6_cmp sa sb >= 0 in
    let hs = if a_first then a.sign else b.sign in
    let ls = if a_first then b.sign else a.sign in
    let he = if a_first then ea else eb in
    let __sf_le = if a_first then eb else ea in
    let hv = if a_first then sa else sb in
    let lv = if a_first then sb else sa in
    let d = he - __sf_le in
    // Past 60 the whole of the smaller value is below the sticky, and shifting
    // one bit at a time that far is only slow.
    let (lv2, st) = if d > 60 then (__sf_l6_zero, if __sf_l6_is_zero lv then 0 else 1)
                    else __sf_l6_shr_sticky lv d in
    if hs == ls then __sf_pack hs (__sf_l6_add hv lv2) he st
    else
      // a - (b + f) with 0 < f < 1 is (a - b - 1) + (1 - f): borrow one and
      // keep the sticky set, because the remainder is not zero
      let diff = if st == 1 then __sf_l6_sub (__sf_l6_sub hv lv2) __sf_l6_one else __sf_l6_sub hv lv2 in
      if __sf_l6_is_zero diff && st == 0 then __sf_zero    // exact cancellation is +0
      else __sf_pack hs diff he st;

// `a - b` is `a + (-b)` for every input except a NaN. Negating one flips its
// sign bit, and an operation handed a NaN propagates the NaN it was GIVEN, not a
// negated copy of it -- so `1.0 - nan` came out as -nan here while every machine
// with a float unit returns +nan. The differential against hardware in
// test/float/rv_float_ops.mere is what found it; the add/mul/div gates never
// subtracted a NaN.
let __sf_sub = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  if __sf_is_nan a then __sf_quiet a
  else if __sf_is_nan b then __sf_quiet b
  else __sf_add a (__sf_neg b);
// ---- contrib/softfloat/mul.mere ----
// contrib/softfloat/mul — IEEE 754 multiplication, in integers only.
//
// This is what the 15-bit limb width was chosen for. Two 53-bit significands
// make a product of up to 106 bits, and the schoolbook loop computes it as
// limb-by-limb products of at most 30 bits each. That fits the narrowest int
// any backend has -- RV32I's signed 32-bit word -- with one condition: the
// carry must be propagated at every step. Accumulating four of them into one
// column before carrying reaches 2^32 and overflows there, so the inner loop
// carries as it goes and no accumulator passes 2^31.

// The 53-bit significand as four limbs in a Vec, so the schoolbook loop can be
// a loop. The fields of a record cannot be indexed.
let __sf_sig_limbs = fn (a: Sf__rv) ->
  let h = if a.exp == 0 then 0 else __sf_hidden_bit in
  let v = vec_new () in
  let _ = vec_push v a.f0 in
  let _ = vec_push v a.f1 in
  let _ = vec_push v a.f2 in
  let _ = vec_push v (a.f3 + h) in
  v;

// p[i+j] += a[i]*b[j], carrying at each step. The bound that matters:
// p < 2^15, a[i]*b[j] < 2^30, carry < 2^16, so the sum stays under 2^31.
let __sf_mul_limbs = fn (a) -> fn (b) ->
  let p = vec_new () in
  let rec zeros = fn (k: int) -> if k <= 0 then () else let _ = vec_push p 0 in zeros (k - 1) in
  let _ = zeros 8 in
  let rec inner = fn (i: int) -> fn (j: int) -> fn (carry: int) ->
    if j >= 4 then vec_set p (i + 4) (vec_get p (i + 4) + carry)
    else
      let t = vec_get p (i + j) + vec_get a i * vec_get b j + carry in
      let _ = vec_set p (i + j) (bit_and t __sf_lmask) in
      inner i (j + 1) (bit_shr t __sf_lbits) in
  let rec outer = fn (i: int) ->
    if i >= 4 then () else let _ = inner i 0 0 in outer (i + 1) in
  let _ = outer 0 in
  p;

// The product, shifted down to the working format: at most 56 bits, which is
// 53 with three below for the guard, the round and the sticky.
//
// The shift is computed from the product's own width, NOT fixed. A fixed
// `P >> 49` is right for two normals -- their product is 105 or 106 bits -- and
// wrong the moment either operand is subnormal, because then the product is
// narrower and the bits below 49 are significand, not sticky. The gate found it
// as `0,1 * 2146435071,4294967295`: the high half matched the hardware and the
// low half came back zero. A tolerance would have accepted it.
let __sf_prod_limb = fn (p) -> fn (i: int) -> if i < 0 || i > 7 then 0 else vec_get p i;

let __sf_prod_bitlen = fn (p) ->
  let rec go = fn (k: int) ->
    if k < 0 then 0
    else if vec_get p k != 0 then k * 15 + __sf_l6_bitlen_limb (vec_get p k) 0
    else go (k - 1) in
  go 7;

// bits [from, from+15) of the product, which may straddle two limbs
let __sf_prod_bits15 = fn (p) -> fn (from: int) ->
  let li = from / 15 in
  let off = from - li * 15 in
  if off == 0 then __sf_prod_limb p li
  else bit_and (bit_or (bit_shr (__sf_prod_limb p li) off)
                       (bit_shl (__sf_prod_limb p (li + 1)) (15 - off))) __sf_lmask;

// is any bit below `n` set?
let __sf_prod_low_nonzero = fn (p) -> fn (n: int) ->
  let rec go = fn (i: int) ->
    if i >= n then 0
    else
      let li = i / 15 in
      let take = if n - i >= 15 then 15 else n - i in
      let v = bit_and (__sf_prod_limb p li) (bit_shl 1 take - 1) in
      if i - li * 15 == 0 && v != 0 then 1 else
      if bit_and (bit_shr (__sf_prod_limb p li) (i - li * 15)) (bit_shl 1 take - 1) != 0 then 1
      else go (i + take) in
  go 0;

let __sf_product_to_l6 = fn (p) ->
  let len = __sf_prod_bitlen p in
  let k = if len > 56 then len - 56 else 0 in
  let st = if k == 0 then 0 else __sf_prod_low_nonzero p k in
  let s = __sf_l6_of_limbs (__sf_prod_bits15 p (k + 75)) (__sf_prod_bits15 p (k + 60))
                      (__sf_prod_bits15 p (k + 45)) (__sf_prod_bits15 p (k + 30))
                      (__sf_prod_bits15 p (k + 15)) (__sf_prod_bits15 p k) in
  (s, k, st);

let __sf_mul = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  let sign = bit_xor a.sign b.sign in
  if __sf_is_snan a then __sf_quiet a
  else if __sf_is_snan b then __sf_quiet b
  else if __sf_is_nan a then a
  else if __sf_is_nan b then b
  else if __sf_is_inf a then (if __sf_is_zero b then __sf_nan else (if sign == 1 then __sf_neg_inf else __sf_inf))
  else if __sf_is_inf b then (if __sf_is_zero a then __sf_nan else (if sign == 1 then __sf_neg_inf else __sf_inf))
  else if __sf_is_zero a || __sf_is_zero b then __sf_mk sign 0 0 0 0 0
  else
    let (s, k, st) = __sf_product_to_l6 (__sf_mul_limbs (__sf_sig_limbs a) (__sf_sig_limbs b)) in
    // value = S * 2^(Ea + Eb - 2150 + k), and pack reads s as `significand<<3`
    // with value = s * 2^(e - 1078), so e = Ea + Eb + k - 1072.
    __sf_pack sign s (__sf_eff_exp a + __sf_eff_exp b + k - 1072) st;
// ---- contrib/softfloat/div.mere ----
// contrib/softfloat/div — IEEE 754 division, in integers only.
//
// Restoring long division: 56 quotient bits, one per round, which is 53 plus the
// three the rounding needs. The remainder at the end is the sticky.
//
// Both significands are normalised to exactly 53 bits FIRST, with the exponent
// paying for the shift. Without that a subnormal divisor makes the true
// quotient far wider than 56 bits and the loop, which produces exactly 56,
// would drop the top of it and hand back a small number where the answer is
// an overflow.

// (significand, effective exponent) with the significand's top bit at 52
let __sf_norm_sig = fn (a: Sf__rv) ->
  let h = if a.exp == 0 then 0 else __sf_hidden_bit in
  let s = __sf_l6_of_limbs 0 0 (a.f3 + h) a.f2 a.f1 a.f0 in
  let rec go = fn (v: L6__rv) -> fn (e: int) ->
    if __sf_l6_bitlen v >= 53 then (v, e) else go (__sf_l6_shl v 1) (e - 1) in
  go s (__sf_eff_exp a);

// floor(a * 2^56 / b), and whether anything was left over.
//
// The loop keeps `2^i * a = q * b + rem` with `rem < b`, and one subtraction
// per step can only hold that if the remainder is already below b when the
// loop starts. Both significands are normalised to 53 bits, so a/b is in
// (0.5, 2) and a CAN be the larger -- the first version began with `rem = a`
// and every quotient with a >= b came back half its true size. The pre-step
// takes that case out: the integer part is 1, and the loop's 56 shifts carry
// it to the top of the answer.
let __sf_divide = fn (a: L6__rv) -> fn (b: L6__rv) ->
  let (r0, q0) = if __sf_l6_cmp a b >= 0 then (__sf_l6_sub a b, __sf_l6_one) else (a, __sf_l6_zero) in
  let rec go = fn (i: int) -> fn (rem: L6__rv) -> fn (q: L6__rv) ->
    if i <= 0 then (q, if __sf_l6_is_zero rem then 0 else 1)
    else
      let r1 = __sf_l6_shl rem 1 in
      let q1 = __sf_l6_shl q 1 in
      if __sf_l6_cmp r1 b >= 0 then go (i - 1) (__sf_l6_sub r1 b) (__sf_l6_add q1 __sf_l6_one)
      else go (i - 1) r1 q1 in
  go 56 r0 q0;

// the normalised significand alone, for the gate's probe: `divide` takes limb
// vectors and the probe has an Sf.
let __sf_sig_limbs_l6 = fn (a: Sf__rv) -> fst (__sf_norm_sig a);

let __sf_fdiv = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  let sign = bit_xor a.sign b.sign in
  if __sf_is_snan a then __sf_quiet a
  else if __sf_is_snan b then __sf_quiet b
  else if __sf_is_nan a then a
  else if __sf_is_nan b then b
  else if __sf_is_inf a then (if __sf_is_inf b then __sf_nan else (if sign == 1 then __sf_neg_inf else __sf_inf))
  else if __sf_is_inf b then __sf_mk sign 0 0 0 0 0
  else if __sf_is_zero a then (if __sf_is_zero b then __sf_nan else __sf_mk sign 0 0 0 0 0)
  else if __sf_is_zero b then (if sign == 1 then __sf_neg_inf else __sf_inf)
  else
    let (na, ea) = __sf_norm_sig a in
    let (nb, eb) = __sf_norm_sig b in
    let (q, st) = __sf_divide na nb in
    // a/b = (A/B) * 2^(Ea - Eb) and q is A * 2^56 / B, so the value is
    // q * 2^(Ea - Eb - 56); pack reads s as `significand<<3` with value
    // s * 2^(e - 1078), so e = Ea - Eb + 1022.
    __sf_pack sign q (ea - eb + 1022) st;
// ---- contrib/softfloat/conv.mere ----
// contrib/softfloat/conv — between a double and the backend's own integer.
//
// Both directions have a rule that was measured rather than assumed:
// int -> double ROUNDS (to nearest, ties to even, so 2^53+1 becomes 2^53 and
// 2^53+3 becomes 2^53+4), and double -> int TRUNCATES toward zero (so -1.9
// becomes -1, not -2).

// The integer's magnitude with the binary point at 0, handed to `pack`, which
// does the normalisation and the rounding. pack reads its argument as
// `significand << 3` with value `s * 2^(e - 1078)`, so a plain integer m is
// `m << 3` at e = 1075.
//
// The magnitude of a negative integer is NOT `0 - n`. For the most negative
// value there is no positive counterpart, and the subtraction wraps back to
// itself: the gate caught `-4611686018427387904` coming out as a different
// double than the hardware's. `n / 2` always has one, so the magnitude is built
// from half of it, doubled in the limbs, with the odd bit put back.
let __sf_mag_limbs = fn (n: int) ->
  if n >= 0 then __sf_l6_of_int n
  else __sf_l6_add (__sf_l6_shl (__sf_l6_of_int (0 - (n / 2))) 1)
              (if bit_and n 1 == 1 then __sf_l6_one else __sf_l6_zero);

let __sf_of_int = fn (n: int) ->
  if n == 0 then __sf_zero
  else __sf_pack (if n < 0 then 1 else 0) (__sf_l6_shl (__sf_mag_limbs n) 3) 1075 0;

// Truncation toward zero. The exponent says how far the significand sits from
// the binary point: 1075 - E bits to the right of it.
let __sf_to_int = fn (a: Sf__rv) ->
  if __sf_is_nan a || __sf_is_zero a then 0
  else
    let h = if a.exp == 0 then 0 else __sf_hidden_bit in
    let s = __sf_l6_of_limbs 0 0 (a.f3 + h) a.f2 a.f1 a.f0 in
    let sh = 1075 - __sf_eff_exp a in
    let m =
      if sh >= 0 then (if sh > 75 then __sf_l6_zero else fst (__sf_l6_shr_sticky s sh))
      else (if 0 - sh > 20 then s else __sf_l6_shl s (0 - sh)) in
    let v = __sf_l6_to_int m in
    if a.sign == 1 then 0 - v else v;
// ---- contrib/softfloat/dec.mere ----
// contrib/softfloat/dec — between a double's bits and its decimal spelling,
// in integers.
//
// The contract is the one the interpreter and the C runtime already share:
//
//   parse:  trim ASCII whitespace, drop '_', then a decimal or hex ("0x..p")
//           number, or inf / infinity / nan; the WHOLE string must be consumed;
//           too large is inf, too small is a signed zero; anything else fails
//           with:  float_of_str: "<s>" is not a valid float
//   print:  %.{p}g for p = 12..17, stopping at the first p whose output parses
//           back to the same bits; append ".0" when the result has none of
//           '.', 'e', 'E', 'n', 'i'  (so integral values print as "42.0" and
//           "inf" / "nan" / "1e+16" are left alone).
//
// Everything here is exact. A double is m * 2^e with m < 2^53, and its decimal
// expansion terminates: multiplying by 2 never lengthens the fraction, dividing
// by 2 adds at most one fraction digit. So the working value is an array of
// base-10 digits, and rounding decisions read real digits instead of guessing.
//
// The digit array is a Vec, least significant digit first, with `scale` naming
// how many of the digits are fraction digits. It is REBUILT by the two scaling
// operations rather than mutated in place -- shifting a Vec's contents to make
// room at the small end costs the same copy and earns another way to be wrong.
// Slow and right first; the day this shows up in a profile, the base can grow
// from 10 to 10^4 without changing a decision.

// ---- the digit array -------------------------------------------------------

// value(d, scale) = sum d[i] * 10^(i - scale), digits LSB first
let __sf__dc_get = fn d -> fn (i: int) ->
  if i < 0 || i >= vec_len d then 0 else vec_get d i;

// multiply by 2^k, k <= 13: carry < 2^13 and digit*2^13 + carry < 2^17, safe
// in a 32-bit int with room to spare
// IN PLACE: multiplying rewrites digits low to high and only ever APPENDS, so
// nothing needs to move. This is the hot direction -- parsing a small value
// multiplies by 2 a thousand times -- and rebuilding the array each pass made
// one parse allocate hundreds of kilobytes on a backend where a region
// reclaims nothing.
let __sf__dc_mul2k = fn d -> fn (k: int) ->
  let n = vec_len d in
  let rec go = fn (i: int) -> fn (carry: int) ->
    if i >= n && carry == 0 then ()
    else if i < n then
      let cur = (vec_get d i) * (bit_shl 1 k) + carry in
      let _ = vec_set d i (cur % 10) in
      go (i + 1) (cur / 10)
    else
      let _ = vec_push d (carry % 10) in
      go (i + 1) (carry / 10) in
  let _ = go 0 0 in
  d;

// divide by 2^k, k <= 13, extending the fraction with the exact remainder:
// at most k new fraction digits, because dividing by 2 in decimal terminates.
// Returns (digits, added) -- the caller owns the scale.
let __sf__dc_div2k = fn d -> fn (k: int) ->
  let n = vec_len d in
  let out = vec_new () in
  // the new fraction digits come from pushing the remainder below the point:
  // rem * 10 / 2^k, repeatedly, until the remainder is 0 -- k steps at most
  let rec down = fn (i: int) -> fn (rem: int) ->
    if i >= n then rem
    else
      let cur = rem * 10 + vec_get d (n - 1 - i) in
      let _ = vec_push out (cur / (bit_shl 1 k)) in     // MSB first, reversed below
      down (i + 1) (cur % (bit_shl 1 k)) in
  let rem0 = down 0 0 in
  let rec ext = fn (rem: int) -> fn (added: int) ->
    if rem == 0 then added
    else
      let cur = rem * 10 in
      let _ = vec_push out (cur / (bit_shl 1 k)) in
      ext (cur % (bit_shl 1 k)) (added + 1) in
  let added = ext rem0 0 in
  // reverse into LSB-first
  let m = vec_len out in
  let fin = vec_new () in
  let rec rev = fn (i: int) ->
    if i >= m then () else let _ = vec_push fin (vec_get out (m - 1 - i)) in rev (i + 1) in
  let _ = rev 0 in
  (fin, added);

// the highest index holding a nonzero digit, or -1 for zero
let __sf__dc_top = fn d ->
  let rec go = fn (i: int) ->
    if i < 0 then 0 - 1
    else if vec_get d i != 0 then i
    else go (i - 1) in
  go (vec_len d - 1);

// any nonzero digit strictly below index `lim`
let __sf__dc_dirty_below = fn d -> fn (lim: int) ->
  let rec go = fn (i: int) ->
    if i >= lim || i >= vec_len d then false
    else if vec_get d i != 0 then true
    else go (i + 1) in
  go 0;

// the integer part (digits at and above `scale`) as an L6 -- caller has kept it
// under 18 digits, which is under 60 bits
let __sf__dc_int_l6 = fn d -> fn (scale: int) ->
  let hi = vec_len d - 1 in
  let rec go = fn (i: int) -> fn (acc: L6__rv) ->
    if i < scale then acc
    else
      let t = __sf_l6_add (__sf_l6_shl acc 3) (__sf_l6_shl acc 1) in    // acc * 10
      go (i - 1) (__sf_l6_add t (__sf_l6_of_int (vec_get d i))) in
  go hi __sf_l6_zero;

// how many digits the integer part has (0 for a pure fraction)
let __sf__dc_intdigits = fn d -> fn (scale: int) ->
  let t = __sf__dc_top d in
  if t < scale then 0 else t - scale + 1;

// ---- decimal value -> Sf ----------------------------------------------------

// Normalise (digits, scale) * 2^0 until the integer part is EXACTLY 56 bits
// (53 + pack's three guard bits), tracking the binary exponent; then let pack
// round. The fraction that remains is sticky. Coarse steps of 13 bits while the
// integer part is clearly far away, single-bit steps for the landing.
let __sf__dc_to_sf = fn (sign: int) -> fn d0 -> fn (scale0: int) ->
  if __sf__dc_top d0 < 0 then (if sign == 1 then __sf_neg_zero else __sf_zero)
  else
    // The leading digit's decimal exponent decides the extremes outright:
    // 10^309 is already past the largest double twice over, and 10^-330 is
    // under half the smallest subnormal -- no digits can pull either back.
    // Without this, "1e1000000" walks a million-digit array to say inf.
    let x = __sf__dc_top d0 - scale0 in
    if x >= 310 then (if sign == 1 then __sf_neg_inf else __sf_inf)
    else if x <= (0 - 330) then (if sign == 1 then __sf_neg_zero else __sf_zero)
    else
    let rec norm = fn d -> fn (scale: int) -> fn (e2: int) ->
      let idig = __sf__dc_intdigits d scale in
      if idig >= 19 then
        let (nd, added) = __sf__dc_div2k d 13 in
        norm nd (scale + added) (e2 + 13)
      else if idig <= 14 then
        // 14 digits stay under 19 after * 2^13, so this cannot bounce off the
        // >= 19 arm above -- 15 would, and the two arms would hand the value
        // back and forth forever
        let nd = __sf__dc_mul2k d 13 in
        norm nd scale (e2 - 13)
      else
        let bl = __sf_l6_bitlen (__sf__dc_int_l6 d scale) in
        if bl > 56 then
          let (nd, added) = __sf__dc_div2k d 1 in
          norm nd (scale + added) (e2 + 1)
        else if bl < 56 then
          let nd = __sf__dc_mul2k d 1 in
          norm nd scale (e2 - 1)
        else (d, scale, e2) in
    let (d, scale, e2) = norm d0 scale0 0 in
    let m56 = __sf__dc_int_l6 d scale in
    let st = if __sf__dc_dirty_below d scale then 1 else 0 in
    // pack reads value = s * 2^(e - 1078); here value = m56 * 2^e2
    __sf_pack sign m56 (e2 + 1078) st;

// ---- Sf -> exact decimal ----------------------------------------------------

// the significand's decimal digits, then scaled by 2^(E - 1075) exactly
let __sf__dc_of_sf = fn (a: Sf__rv) ->
  let (sig, e) = __sf_norm_sig a in
  let d0 = vec_new () in
  let _ = vec_push d0 0 in
  // digits of sig: fold bits in, top first: d = d*2 + bit
  let rec bits = fn (i: int) -> fn d ->
    if i < 0 then d
    else
      let dd = __sf__dc_mul2k d 1 in
      let _ = (if __sf_l6_bit sig i == 1 then vec_set dd 0 (vec_get dd 0 + 1) else ()) in
      bits (i - 1) dd in
  let d1 = bits (__sf_l6_bitlen sig - 1) d0 in
  let sh = e - 1075 in
  if sh >= 0 then
    let rec up = fn d -> fn (k: int) ->
      if k == 0 then d
      else let s = (if k > 13 then 13 else k) in up (__sf__dc_mul2k d s) (k - s) in
    (up d1 sh, 0)
  else
    let rec down = fn d -> fn (scale: int) -> fn (k: int) ->
      if k == 0 then (d, scale)
      else
        let s = (if k > 13 then 13 else k) in
        let (nd, added) = __sf__dc_div2k d s in
        down nd (scale + added) (k - s) in
    down d1 0 (0 - sh);

// ---- %.{p}g ------------------------------------------------------------------

// round the digit sequence to p significant digits, half to even on the exact
// tail; returns (digits msb-first as a Vec, decimal exponent X) with the value
// d[0].d[1..] * 10^X
let __sf__dc_sigdigits = fn d -> fn (scale: int) -> fn (p: int) ->
  let top = __sf__dc_top d in
  let x0 = top - scale in
  // indices top, top-1, ... ; digit i of the output is d[top - i]
  let out = vec_new () in
  let rec take = fn (i: int) ->
    if i >= p then ()
    else let _ = vec_push out (__sf__dc_get d (top - i)) in take (i + 1) in
  let _ = take 0 in
  let nxt = __sf__dc_get d (top - p) in
  let dirty = __sf__dc_dirty_below d (top - p) in
  let roundup =
    if nxt > 5 then true
    else if nxt < 5 then false
    else if dirty then true
    else bit_and (vec_get out (p - 1)) 1 == 1 in
  if roundup then
    let rec carry = fn (i: int) ->
      if i < 0 then 1                                    // carried past the top
      else if vec_get out i == 9 then let _ = vec_set out i 0 in carry (i - 1)
      else let _ = vec_set out i (vec_get out i + 1) in 0 in
    let c = carry (p - 1) in
    if c == 1 then
      // 999.. became 1000..: one digit, then zeros
      let out2 = vec_new () in
      let _ = vec_push out2 1 in
      let rec zs = fn (i: int) -> if i >= p - 1 then () else let _ = vec_push out2 0 in zs (i + 1) in
      let _ = zs 0 in
      (out2, x0 + 1)
    else (out, x0)
  else (out, x0);

let __sf__dc_digit_ch = fn (n: int) -> chr (48 + n);

// strip trailing zeros of the significant digits (never the first digit)
let __sf__dc_lastnz = fn dig ->
  let rec go = fn (i: int) ->
    if i <= 0 then 0
    else if vec_get dig i != 0 then i
    else go (i - 1) in
  go (vec_len dig - 1);

let __sf__dc_fmt_exp = fn (x: int) ->
  let mag = if x < 0 then 0 - x else x in
  let body = str_of_int mag in
  "e" ++ (if x < 0 then "-" else "+") ++ (if mag < 10 then "0" ++ body else body);

// %.{p}g of a nonzero finite value whose exact digits are (d, scale)
let __sf__dc_g = fn (sign: int) -> fn d -> fn (scale: int) -> fn (p: int) ->
  let (dig, x) = __sf__dc_sigdigits d scale p in
  let last = __sf__dc_lastnz dig in
  let s0 =
    if x < (0 - 4) || x >= p then
      // exponent form: d[.ddd]e±XX
      let rec frac = fn (i: int) -> fn (acc: str) ->
        if i > last then acc else frac (i + 1) (acc ++ __sf__dc_digit_ch (vec_get dig i)) in
      __sf__dc_digit_ch (vec_get dig 0)
        ++ (if last >= 1 then "." ++ frac 1 "" else "")
        ++ __sf__dc_fmt_exp x
    else if x >= 0 then
      // ddd[.ddd] -- the point sits after digit x
      let rec go = fn (i: int) -> fn (acc: str) ->
        if i > last && i > x then acc
        else
          let acc2 = (if i == x + 1 then acc ++ "." else acc) in
          go (i + 1) (acc2 ++ __sf__dc_digit_ch (if i <= last then vec_get dig i else 0)) in
      go 0 ""
    else
      // 0.00ddd -- (-x - 1) zeros between the point and the first digit
      let rec zs = fn (i: int) -> fn (acc: str) ->
        if i >= (0 - x) - 1 then acc else zs (i + 1) (acc ++ "0") in
      let rec go = fn (i: int) -> fn (acc: str) ->
        if i > last then acc else go (i + 1) (acc ++ __sf__dc_digit_ch (vec_get dig i)) in
      "0." ++ zs 0 "" ++ go 0 "" in
  (if sign == 1 then "-" else "") ++ s0;

// ---- the parser --------------------------------------------------------------

let __sf__dc_is_ws = fn (c: str) ->
  str_eq c " " || str_eq c "\t" || str_eq c "\n" || str_eq c "\r" || str_eq c "\012";

let __sf__dc_digit = fn (c: str) ->
  let n = ord c in
  if n >= 48 && n <= 57 then n - 48 else 0 - 1;

let __sf__dc_hexdigit = fn (c: str) ->
  let n = ord c in
  if n >= 48 && n <= 57 then n - 48
  else if n >= 97 && n <= 102 then n - 87
  else if n >= 65 && n <= 70 then n - 55
  else 0 - 1;

// trim + drop underscores, in one pass over the raw string
let __sf__dc_clean = fn (s: str) ->
  let n = str_len s in
  let rec lead = fn (i: int) -> if i < n && __sf__dc_is_ws (char_at s i) then lead (i + 1) else i in
  let rec trail = fn (i: int) -> if i > 0 && __sf__dc_is_ws (char_at s (i - 1)) then trail (i - 1) else i in
  let a = lead 0 in
  let b = trail n in
  let rec go = fn (i: int) -> fn (acc: str) ->
    if i >= b then acc
    else
      let c = char_at s i in
      go (i + 1) (if str_eq c "_" then acc else acc ++ c) in
  go a "";

// hex: 0x H [. H] [p±d] -- mantissa bits are the digits, the exponent is a
// power of two, so this never needs the decimal machinery: collect up to 56
// bits, everything further is sticky, and pack does the rest.
let __sf__dc_parse_hex = fn (sign: int) -> fn (t: str) -> fn (fail_s: str) ->
  let n = str_len t in
  let rec mant = fn (i: int) -> fn (acc: L6__rv) -> fn (bits: int) -> fn (st: int) ->
                 fn (fdig: int) -> fn (seen: int) -> fn (dot: int) ->
    if i >= n then (i, acc, bits, st, fdig, seen, dot)
    else
      let c = char_at t i in
      if str_eq c "." && dot == 0 then mant (i + 1) acc bits st fdig seen 1
      else
        let h = __sf__dc_hexdigit c in
        if h < 0 then (i, acc, bits, st, fdig, seen, dot)
        else
          let fd = fdig + (if dot == 1 then 1 else 0) in
          if bits >= 57 then
            // No more room: the digit is sticky. An INTEGER digit skipped here
            // still scales the value by 16, which is fdig - 1 in the exponent
            // pexp - 4*fdig; a FRACTION digit skipped here scales nothing.
            mant (i + 1) acc bits (bit_or st (if h != 0 then 1 else 0))
                 (fdig + (if dot == 1 then 0 else 0 - 1)) seen dot
          else
            mant (i + 1) (__sf_l6_add (__sf_l6_shl acc 4) (__sf_l6_of_int h))
                 (if bits == 0 && h == 0 then 0 else __sf_l6_bitlen (__sf_l6_add (__sf_l6_shl acc 4) (__sf_l6_of_int h)))
                 st fd (seen + 1) dot in
  let (i1, m, _, st, fdig, seen, _) = mant 0 __sf_l6_zero 0 0 0 0 0 in
  if seen == 0 then fail fail_s else
  let (i2, pexp) =
    if i1 < n && (str_eq (char_at t i1) "p" || str_eq (char_at t i1) "P") then
      let rec pe = fn (i: int) -> fn (acc: int) -> fn (any: int) -> fn (psign: int) ->
        if i >= n then (if any == 0 then (0 - 1, 0) else (i, psign * acc))
        else
          let c = char_at t i in
          if any == 0 && str_eq c "-" then pe (i + 1) acc 0 (0 - 1)
          else if any == 0 && str_eq c "+" then pe (i + 1) acc 0 psign
          else
            let dg = __sf__dc_digit c in
            if dg < 0 then (if any == 0 then (0 - 1, 0) else (i, psign * acc))
            else pe (i + 1) (if acc > 100000 then acc else acc * 10 + dg) (any + 1) psign in
      pe (i1 + 1) 0 0 1
    else (i1, 0) in
  if i2 != n || i2 < 0 then fail fail_s else
  if __sf_l6_is_zero m && st == 0 then (if sign == 1 then __sf_neg_zero else __sf_zero) else
  // value = m * 2^(pexp - 4*fdig); normalise m to 56 bits for pack
  let rec up = fn (v: L6__rv) -> fn (e: int) ->
    if __sf_l6_bitlen v >= 56 then (v, e) else up (__sf_l6_shl v 1) (e - 1) in
  let rec dn = fn (v: L6__rv) -> fn (e: int) -> fn (stx: int) ->
    if __sf_l6_bitlen v <= 56 then (v, e, stx)
    else let pr = __sf_l6_shr_sticky v 1 in dn (fst pr) (e + 1) (bit_or stx (snd pr)) in
  let (m1, e1) = up m (pexp - 4 * fdig) in
  let (m2, e2, st2) = dn m1 e1 st in
  __sf_pack sign m2 (e2 + 1078) st2;

// decimal or hex or the named specials; the whole string or nothing
let __sf_sf_of_dec = fn (s: str) ->
  let fail_s = "float_of_str: \"" ++ s ++ "\" is not a valid float" in
  let t0 = __sf__dc_clean s in
  let (sign, t) =
    if str_len t0 > 0 && str_eq (char_at t0 0) "-" then (1, substring t0 1 (str_len t0))
    else if str_len t0 > 0 && str_eq (char_at t0 0) "+" then (0, substring t0 1 (str_len t0))
    else (0, t0) in
  if str_eq t "inf" || str_eq t "infinity" then (if sign == 1 then __sf_neg_inf else __sf_inf)
  else if str_eq t "nan" then __sf_nan
  else if str_len t >= 2 && str_eq (substring t 0 2) "0x" || str_len t >= 2 && str_eq (substring t 0 2) "0X" then
    __sf__dc_parse_hex sign (substring t 2 (str_len t)) fail_s
  else
    let n = str_len t in
    // digits [. digits] [e±d]; at least one digit somewhere before the e
    let d = vec_new () in                                // MSB first while reading
    let rec mant = fn (i: int) -> fn (fdig: int) -> fn (seen: int) -> fn (dot: int) ->
      if i >= n then (i, fdig, seen)
      else
        let c = char_at t i in
        if str_eq c "." && dot == 0 then mant (i + 1) fdig seen 1
        else
          let dg = __sf__dc_digit c in
          if dg < 0 then (i, fdig, seen)
          else
            let _ = vec_push d dg in
            mant (i + 1) (fdig + (if dot == 1 then 1 else 0)) (seen + 1) dot in
    let (i1, fdig, seen) = mant 0 0 0 0 in
    if seen == 0 then fail fail_s else
    let (i2, dexp) =
      if i1 < n && (str_eq (char_at t i1) "e" || str_eq (char_at t i1) "E") then
        let rec pe = fn (i: int) -> fn (acc: int) -> fn (any: int) -> fn (psign: int) ->
          if i >= n then (if any == 0 then (0 - 1, 0) else (i, psign * acc))
          else
            let c = char_at t i in
            if any == 0 && str_eq c "-" then pe (i + 1) acc 0 (0 - 1)
            else if any == 0 && str_eq c "+" then pe (i + 1) acc 0 psign
            else
              let dg = __sf__dc_digit c in
              if dg < 0 then (if any == 0 then (0 - 1, 0) else (i, psign * acc))
              // the exponent saturates: past |10^6| the value is decided by the
              // digit count alone, and 10^6 digits is not a real input
              else pe (i + 1) (if acc > 1000000 then acc else acc * 10 + dg) (any + 1) psign in
        pe (i1 + 1) 0 0 1
      else (i1, 0) in
    if i2 != n || i2 < 0 then fail fail_s else
    // value = digits * 10^(dexp - fdig): LSB-first array, scale from the point
    let m = vec_len d in
    let lsb = vec_new () in
    let rec rev = fn (i: int) ->
      if i >= m then () else let _ = vec_push lsb (vec_get d (m - 1 - i)) in rev (i + 1) in
    let _ = rev 0 in
    let k = dexp - fdig in
    let topnz = __sf__dc_top lsb in
    if topnz < 0 then (if sign == 1 then __sf_neg_zero else __sf_zero)
    else if topnz + k >= 310 then (if sign == 1 then __sf_neg_inf else __sf_inf)
    else if topnz + k <= (0 - 330) then (if sign == 1 then __sf_neg_zero else __sf_zero)
    // fold 10^k in: k > 0 appends zeros at the LSB end; k < 0 raises the scale
    else if k >= 0 then
      let shifted = vec_new () in
      let rec zs = fn (i: int) -> if i >= k then () else let _ = vec_push shifted 0 in zs (i + 1) in
      let _ = zs 0 in
      let rec cp = fn (i: int) -> if i >= m then () else let _ = vec_push shifted (vec_get lsb i) in cp (i + 1) in
      let _ = cp 0 in
      __sf__dc_to_sf sign shifted 0
    else
      __sf__dc_to_sf sign lsb (0 - k);

// ---- the printer --------------------------------------------------------------

let __sf__dc_sf_eq = fn (a: Sf__rv) -> fn (b: Sf__rv) ->
  a.sign == b.sign && a.exp == b.exp
  && a.f3 == b.f3 && a.f2 == b.f2 && a.f1 == b.f1 && a.f0 == b.f0;

let __sf__dc_has_mark = fn (s: str) ->
  let rec go = fn (i: int) ->
    if i >= str_len s then false
    else
      let c = char_at s i in
      if str_eq c "." || str_eq c "e" || str_eq c "E" || str_eq c "n" || str_eq c "i" then true
      else go (i + 1) in
  go 0;

let __sf_dec_of_sf = fn (a: Sf__rv) ->
  let s0 =
    if __sf_is_nan a then "nan"
    else if __sf_is_inf a then (if a.sign == 1 then "-inf" else "inf")
    else if __sf_is_zero a then (if a.sign == 1 then "-0" else "0")
    else
      let (d, scale) = __sf__dc_of_sf a in
      let rec go = fn (p: int) ->
        let s = __sf__dc_g a.sign d scale p in
        if p >= 17 then s
        else if __sf__dc_sf_eq (__sf_sf_of_dec s) a then s
        else go (p + 1) in
      go 12 in
  if __sf__dc_has_mark s0 then s0 else s0 ++ ".0";
// ---- contrib/softfloat/bits.mere ----
// The bridge between hardware doubles and this library's limbs.
//
// This is the ONE file here that mentions `float`, and the gate checks that the
// others do not: the library has to compile for a backend that has no float at
// all, and a bridge is exactly the thing that cannot honour that. It lives in
// the library rather than in the gates because the RV32I prelude needs it too --
// that backend's `+` on floats decodes, adds in limbs, and re-encodes, so the
// bridge is the load-bearing half of float arithmetic there.
//
// Everything here is a BIT operation on the two 32-bit halves, never an
// arithmetic one, and that is what makes it work on a target whose int is a
// SIGNED 32-bit word. `float_bits_hi (-1.0)` is 3220176896, which does not fit
// one; on RV32I the same call returns the same 32 bits as a negative number.
// Masking a field out of it is right either way. Adding or comparing would not
// be.

let __sf_br_low15 = 32767;
let __sf_br_low20 = 1048575;
let __sf_br_low13 = 8191;

let __sf_sf_of_hi_lo = fn (hi: int) -> fn (lo: int) ->
  let fh = bit_and hi __sf_br_low20 in
  __sf_mk (bit_and (bit_shr hi 31) 1)
     (bit_and (bit_shr hi 20) 2047)
     (bit_and (bit_shr fh 13) 127)
     (bit_or (bit_and (bit_shr lo 30) 3) (bit_shl (bit_and fh __sf_br_low13) 2))
     (bit_and (bit_shr lo 15) __sf_br_low15)
     (bit_and lo __sf_br_low15);

let __sf_hi_of_sf = fn (a: Sf__rv) ->
  bit_or (bit_or (bit_shl a.sign 31) (bit_shl a.exp 20))
         (bit_or (bit_shr a.f2 2) (bit_shl a.f3 13));

let __sf_lo_of_sf = fn (a: Sf__rv) ->
  bit_or (bit_or a.f0 (bit_shl a.f1 15)) (bit_shl (bit_and a.f2 3) 30);

let __sf_sf_of_float = fn (x: float) -> __sf_sf_of_hi_lo (float_bits_hi x) (float_bits_lo x);
let __sf_float_of_sf = fn (a: Sf__rv) -> float_of_bits (__sf_hi_of_sf a) (__sf_lo_of_sf a);
|sf}
