#!/usr/bin/env python3
"""entities.json -> contrib/html/entities.mere (see gen_html_entities.sh)."""
import json, sys

src, dst = sys.argv[1], sys.argv[2]
data = json.load(open(src, encoding="utf-8"))

NAME_W = 32
recs = []
for key in sorted(data):
    name = key[1:]                     # drop the leading "&"
    assert len(name) <= NAME_W, name
    cps = data[key]["codepoints"]
    cp1 = cps[0]
    cp2 = cps[1] if len(cps) > 1 else 0
    recs.append("%-*s%06x%06x" % (NAME_W, name, cp1, cp2))
recs.sort()
table = "".join(recs)
assert "\0" not in table and all(ord(c) < 128 for c in table)

with open(dst, "w", encoding="utf-8") as f:
    f.write('''// Generated by scripts/gen_html_entities.sh — do not edit.
//
// The %d named character references, as one string of fixed-width records so that
// a binary search can find one by index arithmetic and no index structure has to
// be built at startup. 44 characters each: the name without its leading `&`,
// space-padded to %d, then two code points as six hex digits (000000 for the
// second when there is only one).
//
// Space pads rather than NUL for two reasons: a Mere str cannot carry a NUL
// through the compiled backends, and space sorts below every character a name
// uses, so the padded order is the plain order and the search needs no special
// case for a short name.

let _ent_w = 44;
let _ent_n = %d;

let _ent_table = "%s";
''' % (len(recs), NAME_W, len(recs), table))
print("%d records, %d chars" % (len(recs), len(table)))
