#!/usr/bin/env python3
"""encodings.json -> contrib/encoding/labels.mere (see gen_encoding_labels.sh)."""
import json, sys
src, dst = sys.argv[1], sys.argv[2]
groups = json.load(open(src, encoding="utf-8"))
LW, NW = 20, 16
recs = []
for g in groups:
    for e in g["encodings"]:
        name = e["name"].lower()          # the convention this directory already uses
        for lab in e["labels"]:
            assert len(lab) <= LW and len(name) <= NW, (lab, name)
            recs.append("%-*s%-*s" % (LW, lab, NW, name))
recs.sort()
table = "".join(recs)
assert all(ord(c) < 128 for c in table) and "\0" not in table
open(dst, "w", encoding="utf-8").write('''// Generated by scripts/gen_encoding_labels.sh — do not edit.
//
// Every label the Encoding Standard defines, and what it names — %d of them for
// %d encodings. Fixed-width records in one sorted string, binary-searched by index
// arithmetic: the shape Q-028 settled for the Unicode tables and the HTML named
// references. %d characters for the label, %d for the name, space-padded.
//
// This lists labels for encodings nothing here decodes, and that is the point.
// `label_of` answers what a label names; whether this directory can decode it is a
// different question, and `decode` already answers None for the ones it cannot.
// Listing only the decodable ones made a page declaring `iso-8859-2` look like a
// page declaring nothing at all — which the HTML standard treats differently.

let _lbl_w = %d;
let _lbl_n = %d;
let _lbl_table = "%s";

module Labels {
  let _label_at = fn (i: int) ->
    str_trim (substring _lbl_table (i * _lbl_w) (i * _lbl_w + %d));
  let _name_at = fn (i: int) ->
    str_trim (substring _lbl_table (i * _lbl_w + %d) ((i + 1) * _lbl_w));

  let find = fn (want: str) ->
    let rec bs = fn (lo: int) -> fn (hi: int) ->
      if lo >= hi then None
      else
        let mid = (lo + hi) / 2 in
        let l = _label_at mid in
        if l == want then Some (_name_at mid)
        else if l < want then bs (mid + 1) hi
        else bs lo mid in
    bs 0 _lbl_n;
}
''' % (len(recs), sum(len(g["encodings"]) for g in groups), LW, NW,
       LW + NW, len(recs), table, LW, LW))
print("%d labels, %d chars" % (len(recs), len(table)))
