#!/bin/sh
# scripts/gen_introspection_sdl.sh — the introspection schema, from graphql-js.
#
# The introspection types (`__Schema`, `__Type`, `__Field`, `__InputValue`,
# `__EnumValue`, `__Directive`, `__TypeKind`, `__DirectiveLocation`) and the
# built-in directives are NORMATIVE: the specification fixes their field names,
# their types, their nullability and their order. Typing them out is a
# transcription, and a transcription of 200 lines has a mistake in it.
#
# So they are GENERATED from graphql-js's own type objects and COMMITTED, the same
# arrangement as the HPACK tables: `graphql_intro_parity.sh` regenerates and diffs,
# so a drift in the oracle shows up as a diff rather than as a silent divergence.
#
# The output is one Mere string constant. It is fed to `Gparse.document` like any
# other SDL, which is the whole point — introspection is answered by the ordinary
# executor against ordinary type definitions, not by a second code path.
#
# Usage:
#   sh scripts/gen_introspection_sdl.sh > contrib/graphql/introspection_sdl.mere

set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)

GQL_DIR=""
for cand in "$ROOT/node_modules/graphql" "$(npm root -g 2>/dev/null)/graphql"; do
  [ -f "$cand/package.json" ] && { GQL_DIR=$cand; break; }
done
[ -n "$GQL_DIR" ] || { echo "gen_introspection_sdl: graphql-js not found" >&2; exit 1; }
VER=$(node -p "require('$GQL_DIR/package.json').version")

node --input-type=module -e "
import * as g from '$GQL_DIR/index.js';

// A directive's SDL, built from the oracle's own object rather than typed out.
function printDirective(d) {
  const args = d.args.map(a => {
    // graphql-js 17 keeps an argument default in a.default.value; a.defaultValue
    // is undefined. Reading the old field silently dropped the default on
    // deprecated's reason argument, and the oracle's own introspection said so.
    const dv = a.default === undefined ? ''
      : ' = ' + g.print(g.astFromValue(a.default.value, a.type));
    return a.name + ': ' + String(a.type) + dv;
  });
  return 'directive @' + d.name
    + (args.length ? '(' + args.join(', ') + ')' : '')
    + (d.isRepeatable ? ' repeatable' : '')
    + ' on ' + d.locations.join(' | ');
}

const parts = Object.values(g.introspectionTypes).map(t => g.printType(t));
for (const d of g.specifiedDirectives) parts.push(printDirective(d));
process.stdout.write(parts.join('\n\n') + '\n');
" > /tmp/gen_intro_sdl.$$

# Descriptions are DROPPED, and that is a decision rather than an omission.
#
# They are prose: hundreds of lines of it, in block strings, that no introspection
# answer this executor produces depends on — `description` resolves to null here
# either way. Keeping them would put the oracle's English into a committed Mere
# file and make every graphql-js release a diff in this repo for reasons that are
# not about GraphQL.
#
# The gate asserts `description` is null on both sides, so this is a stated gap and
# not a hidden one.
node -e "
const fs = require('fs');
const src = fs.readFileSync('/tmp/gen_intro_sdl.$$', 'utf8');
// Strip block strings, then collapse the blank lines they leave behind.
const out = src.replace(/\"\"\"[\s\S]*?\"\"\"\n?/g, '')
               .replace(/\n{3,}/g, '\n\n')
               .replace(/\{\n\n/g, '{\n');
const esc = out.replace(/\\\\/g, '\\\\\\\\')
               .replace(/\"/g, '\\\\\"')
               .replace(/\{/g, '\\\\{')
               .replace(/\n/g, '\\\\n');
process.stdout.write(esc);
" > /tmp/gen_intro_esc.$$

cat <<HDR
// GENERATED by scripts/gen_introspection_sdl.sh from graphql-js $VER — do not edit.
//
// The introspection schema: \`__Schema\`, \`__Type\`, \`__Field\`, \`__InputValue\`,
// \`__EnumValue\`, \`__Directive\`, \`__TypeKind\`, \`__DirectiveLocation\`, and the
// built-in directives. The specification fixes every name, type and nullability
// here, so this is normative text and typing it out would be a transcription.
//
// It is ordinary SDL, parsed by \`Gparse.document\` like any other. Introspection is
// answered by the ordinary executor against these definitions — there is no second
// code path for it, which is the reason to have the file at all.
//
// DESCRIPTIONS ARE DROPPED. They are prose that no answer here depends on
// (\`description\` resolves to null), and keeping them would put the oracle's English
// into this repo and make every graphql-js release a diff. The gate asserts
// \`description\` is null on both sides, so the gap is stated.
//
// Regenerate with:
//   sh scripts/gen_introspection_sdl.sh > contrib/graphql/introspection_sdl.mere

module Gintro {
  let sdl = "$(cat /tmp/gen_intro_esc.$$)";
}
HDR
rm -f /tmp/gen_intro_sdl.$$ /tmp/gen_intro_esc.$$
