#!/bin/sh
# scripts/gen_hpack_tables.sh — generate contrib/http2/hpack_table.mere.
#
# HPACK has two tables and neither can be computed: the static table is 61
# name/value pairs listed in RFC 7541 Appendix A, and the Huffman code is 257
# (code, length) pairs listed in Appendix B. Both are transcriptions, so they are
# GENERATED from a machine-readable copy and the result is committed and diffed on
# every run — the arrangement contrib/unicode and contrib/encoding already use.
#
# THE SOURCE HERE IS THE SAME LIBRARY THE GATE USES AS ITS ORACLE, AND THAT IS A
# REAL WEAKNESS: a differential test cannot catch an error in a table both sides
# share. It is stated rather than papered over, and it is why
# `scripts/hpack_parity.sh` has a section that decodes a header block produced by
# grpc-go — a third implementation, in another language, that never saw either of
# these tables. That section is what actually checks them.
#
# The Huffman code is canonical: verified here rather than assumed — codes are
# contiguous within each length and ordered by symbol, so decoding needs only
# per-length counts and first codes, and no tree.
#
# Usage:
#   sh scripts/gen_hpack_tables.sh          # write the file
#   sh scripts/gen_hpack_tables.sh --check  # fail if it would change

set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/contrib/http2/hpack_table.mere"

command -v python3 >/dev/null 2>&1 || { echo "gen_hpack_tables: python3 absent, skipping"; exit 0; }
python3 -c "import hpack" 2>/dev/null || { echo "gen_hpack_tables: hpack absent, skipping"; exit 0; }

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

python3 - "$TMP/out.mere" <<'PY'
import sys
from hpack.table import HeaderTable
from hpack.huffman_constants import REQUEST_CODES as C, REQUEST_CODES_LENGTH as L

order = sorted(range(257), key=lambda s: (L[s], C[s]))
lengths = sorted({L[s] for s in order})
count, first_code, first_index = {}, {}, {}
idx = 0
for l in lengths:
    ss = [s for s in order if L[s] == l]
    count[l] = len(ss)
    first_code[l] = C[ss[0]]
    first_index[l] = idx
    idx += len(ss)
    # asserted, not assumed: canonical decoding is only valid if these hold
    assert [C[s] for s in ss] == list(range(C[ss[0]], C[ss[0]] + len(ss))), l
    assert ss == sorted(ss), l

def esc(b):
    s = b.decode("ascii")
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("{", "\\{")

ent = ",\n    ".join(f'("{esc(n)}", "{esc(v)}")' for n, v in HeaderTable.STATIC_TABLE)
syms = "".join(f"{s:04x}" for s in order)

def chain(name, d):
    body = "\n    ".join(f"if l == {l} then {d[l]} else" for l in lengths)
    return f"  let {name} = fn (l: int) ->\n    {body} 0;\n"

with open(sys.argv[1], "w") as f:
    f.write(f"""// contrib/http2/hpack_table.mere — GENERATED by scripts/gen_hpack_tables.sh.
// DO NOT EDIT. Regenerate and commit; the harness diffs this file on every run.
//
// Two tables that cannot be computed, only transcribed:
//
//   * the static table, RFC 7541 Appendix A, 61 entries, indexed from 1
//   * the Huffman code, RFC 7541 Appendix B, 257 symbols (256 octets + EOS)
//
// The Huffman code is CANONICAL — codes are contiguous within each length and
// ordered by symbol — which the generator asserts rather than assumes. That is
// what lets a decoder work from per-length counts and first codes with no tree.
//
// Symbols are stored in (length, code) order as 16 bits each in hex, so a symbol
// lookup is an index rather than a walk. 257 symbols need 9 bits, so 8 would not
// have been enough: EOS is 256.

module HpackTable {{

  let static_count = {len(HeaderTable.STATIC_TABLE)};

  let static_entries = [
    {ent}
  ];

  // symbols in (length, code) order, four hex digits each
  let huff_syms_hex = "{syms}";
  let huff_sym_count = {len(order)};
  let huff_min_len = {lengths[0]};
  let huff_max_len = {lengths[-1]};

{chain("huff_count", count)}
{chain("huff_first_code", first_code)}
{chain("huff_first_index", first_index)}}}
""")
print(f"static={len(HeaderTable.STATIC_TABLE)} symbols={len(order)} lengths={len(lengths)}")
PY

if [ "$1" = "--check" ]; then
  if diff -q "$OUT" "$TMP/out.mere" >/dev/null 2>&1; then
    echo "gen_hpack_tables: ok (generated file matches what is committed)"
  else
    echo "gen_hpack_tables: FAILED — the committed table is not what the generator produces"
    diff "$OUT" "$TMP/out.mere" | head -20
    exit 1
  fi
else
  cp "$TMP/out.mere" "$OUT"
  echo "gen_hpack_tables: wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
fi
