#!/usr/bin/env python3
"""Rename contrib/softfloat's top-level names into a private namespace.

The RV32I prelude needs this library's arithmetic, because that backend has no
float and `+` on two floats has to be computed in integers. The prelude is
PREPENDED to the user's source, so anything it defines can be shadowed by a
top-level binding in the program -- and the program's `add` would then be what
the prelude's float `+` calls. mere-ruby has 806 top-level names and happens not
to collide with any of these 76, which is luck rather than a design.

So the injected copy is renamed: lowercase names take a `__sf_` prefix and type
names take a `__rv` suffix (a type cannot start with an underscore). The library
keeps its plain names for everyone who imports it directly. One source, two
namespaces -- rather than a second copy that drifts.

The rename is token-aware: identifiers inside comments and string literals are
left alone, and so is anything after a `.`, which is a record field and not a
binding. Field names that collide with top-level names would make the rename
ambiguous, so that is checked rather than assumed.
"""
import re
import sys
from pathlib import Path

# Dependency order: each file may use what the ones before it defined.
ORDER = ["limbs.mere", "softfloat.mere", "add.mere", "mul.mere", "div.mere",
         "conv.mere", "dec.mere", "bits.mere"]

root = Path(sys.argv[1])
src_dir = root / "contrib" / "softfloat"

texts = {}
for name in ORDER:
    texts[name] = (src_dir / name).read_text(encoding="utf-8")

missing = sorted(p.name for p in src_dir.glob("*.mere") if p.name not in ORDER)
if missing:
    sys.exit("gen_rv_softfloat: %s is in the library but not in ORDER -- add it "
             "in dependency order, or the prelude silently omits it" % ", ".join(missing))

LET = re.compile(r"^let\s+(?:rec\s+)?([A-Za-z_][A-Za-z_0-9]*)", re.M)
TYPE = re.compile(r"^type\s+([A-Za-z_][A-Za-z_0-9]*)", re.M)
FIELD = re.compile(r"^type\s+[A-Za-z_][A-Za-z_0-9]*\s*=\s*\{([^}]*)\}", re.M)

lets, types, fields = set(), set(), set()
for name in ORDER:
    t = texts[name]
    lets |= set(LET.findall(t))
    types |= set(TYPE.findall(t))
    for body in FIELD.findall(t):
        for part in body.split(","):
            if ":" in part:
                fields.add(part.split(":")[0].strip())

clash = (lets | types) & fields
if clash:
    sys.exit("gen_rv_softfloat: %s is both a top-level name and a record field; "
             "the rename cannot tell them apart" % ", ".join(sorted(clash)))

rename = {n: "__sf_" + n for n in lets}
rename.update({n: n + "__rv" for n in types})

TOKEN = re.compile(r'//[^\n]*|"(?:[^"\\]|\\.)*"|\.\s*[A-Za-z_][A-Za-z_0-9]*'
                   r'|[A-Za-z_][A-Za-z_0-9]*')

def rewrite(text):
    def sub(m):
        s = m.group(0)
        # comments, strings and field accesses pass through untouched
        if s[0] in '/".':
            return s
        return rename.get(s, s)
    return TOKEN.sub(sub, text)

out = []
out.append("(* rv_softfloat.ml — GENERATED by scripts/gen_rv_softfloat.py from\n"
           "   contrib/softfloat. DO NOT EDIT: regenerate and commit, and\n"
           "   `sh scripts/gen_rv_softfloat.sh --check` diffs it on every run.\n\n"
           "   Every top-level name is renamed into a private namespace so that a\n"
           "   user program's own `add` cannot become what float `+` calls. See the\n"
           "   generator for why that is not paranoia. *)\n")
out.append("let contents = {sf|")
for name in ORDER:
    body = rewrite(texts[name])
    # imports are how the library finds its parts on disk; concatenated in order
    # they are already satisfied, and the -rv path has no file system to resolve
    # them against anyway.
    body = "\n".join(l for l in body.split("\n") if not l.startswith("import "))
    out.append("// ---- contrib/softfloat/%s ----" % name)
    out.append(body.rstrip())
out.append("|sf}")
print("\n".join(out))
